export const metadata = {
  title: "Terms of Service — ResumeForge",
  description: "Terms governing use of ResumeForge.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 text-white">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <a href="/" className="text-sm text-amber-400 hover:underline mb-8 inline-block">← Back to home</a>
        <h1 className="text-3xl sm:text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-white/50 mb-10">Last updated: May 18, 2026</p>

        <div className="space-y-8 text-white/80 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance</h2>
            <p>
              By using ResumeForge ("the Service"), you agree to these terms. If you don't agree, don't use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. What you can do</h2>
            <p>
              You can use ResumeForge to generate AI rewrites of resumes, cover letters, and LinkedIn profiles for
              personal, non-commercial use. You retain all rights to the content you submit and the outputs we generate
              for you.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. What you can't do</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Reverse-engineer, scrape, or attempt to extract our prompts or system architecture.</li>
              <li>Use the Service to generate content that is illegal, defamatory, harassing, or fraudulent.</li>
              <li>Submit someone else's resume or personal information without their permission.</li>
              <li>Resell access to the Service or pass off generated outputs as a paid service to others.</li>
              <li>Use automated tools to abuse free trial limits or create multiple accounts.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Pricing & payments</h2>
            <p className="mb-3">ResumeForge offers:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Free trial:</strong> one use of each tool per account.</li>
              <li><strong>Boost Pack:</strong> $14 CAD one-time purchase for 5 uses of each tool (15 total). Credits never expire.</li>
              <li><strong>Pro:</strong> $19 CAD/month for unlimited use. Cancel anytime through Stripe's billing portal.</li>
            </ul>
            <p className="mt-3">
              Payments are processed by Stripe. All prices in Canadian Dollars (CAD). Prices may change with notice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Refunds</h2>
            <p>
              <strong>Boost Pack:</strong> refundable within 7 days if you've used 2 or fewer credits.
              <br />
              <strong>Pro subscription:</strong> cancel anytime; you keep access until the end of the current billing
              period. No partial refunds for the current month.
              <br />
              For refund requests, email{" "}
              <a href="mailto:hello@resumeforge.ca" className="text-amber-400 hover:underline">hello@resumeforge.ca</a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. No guarantees</h2>
            <p>
              ResumeForge is a tool — not a guarantee of employment. We do our best to produce high-quality outputs,
              but we cannot guarantee that using our tool will result in interviews, job offers, or any specific
              career outcome. Hiring decisions are made by employers based on many factors outside our control.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. AI-generated content</h2>
            <p>
              Outputs are generated by AI and should be reviewed before submission to any employer. We are not
              responsible for inaccuracies, fabrications, or omissions in generated content. You are responsible for
              verifying that any resume or cover letter you submit accurately represents your experience.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Service availability</h2>
            <p>
              We aim for high uptime but make no guarantees. The Service may be temporarily unavailable for
              maintenance, upgrades, or due to issues with third-party providers (Stripe, Anthropic, Supabase, Vercel).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Account termination</h2>
            <p>
              You can delete your account at any time. We may suspend or terminate accounts that violate these
              terms, abuse the Service, or attempt to defraud us.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Limitation of liability</h2>
            <p>
              ResumeForge is provided "as is" without warranties. To the maximum extent permitted by law, our total
              liability for any claim arising from your use of the Service is limited to the amount you paid us in
              the 30 days preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Governing law</h2>
            <p>
              These terms are governed by the laws of Alberta, Canada. Any disputes will be resolved in the courts
              of Alberta.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Changes</h2>
            <p>
              We may update these terms occasionally. Material changes will be communicated by email or via the
              site. Continued use after changes means you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">13. Contact</h2>
            <p>
              Questions:{" "}
              <a href="mailto:hello@resumeforge.ca" className="text-amber-400 hover:underline">hello@resumeforge.ca</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
